version: '3.9'

services:
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "3007:3007"
    environment:
      PORT: 3007
      DATABASE_URL: ${DATABASE_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE}
      RABBITMQ_EXCHANGE: ${RABBITMQ_EXCHANGE}
      RABBITMQ_ROUTING_KEY: ${RABBITMQ_ROUTING_KEY}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_TTL: ${REDIS_TTL}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      UPLOAD_SERVICE_URL: ${UPLOAD_SERVICE_URL}
      KAFKA_BROKER: ${KAFKA_BROKER}
      KAFKA_CLIENT_ID: ${KAFKA_CLIENT_ID}
      KAFKA_GROUP_ID: ${KAFKA_GROUP_ID}
      JWT_SECRET: ${JWT_SECRET}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      MAIL_HOST: ${MAIL_HOST}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
    command: sh -c "npx prisma migrate deploy && node dist/main"
    networks:
      my_custom_network:
        ipv4_address: ${APP_IP}

networks:
  my_custom_network:
    external: true

